cluster_name: cade-test-1

max_workers: 1

provider:
    type: gcp
    region: us-west1
    availability_zone: us-west1-a
    project_id: anyscale-dev

docker:
  image: rayproject/ray:1.12.2-py37-cu112
  container_name: ray_container

setup_commands: []

auth:
    ssh_user: ubuntu

